name: meditation_app
description: "A new Flutter Meditation App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/topic/
     - assets/images/home/
     - assets/images/navbar/
     - assets/images/course/

  fonts:
     - family: HelveticaNeue
       fonts:
         - asset: assets/fonts/HelveticaNeueBold.otf
           weight: 700
         - asset: assets/fonts/HelveticaNeueMedium.otf
           weight: 600
         - asset: assets/fonts/HelveticaNeue-Regular.otf
           weight: 400
         - asset: assets/fonts/HelveticaNeueLight.otf
           weight: 300
         - asset: assets/fonts/HelveticaNeueThin.otf
           weight: 200
